import { TransponderData } from "@/app/services/transponderService";

export const acuraTransponderData: TransponderData[] = [
  {
    id: "ACURA-TL-2004-2008",
    make: "ACURA",
    model: "TL",
    yearStart: 2004,
    yearEnd: 2008,
    transponderType: "Honda G",
    chipType: JSON.stringify(["G8D", "ID46", "PCF7936"]),
    compatibleParts: JSON.stringify(["35111-SEP-307", "35111-SEP-A01"]),
    frequency: "315 MHz",
    notes: "First generation transponder system",
    dualSystem: false,
  },
  {
    id: "ACURA-MDX-2007-2013",
    make: "ACURA",
    model: "MDX",
    yearStart: 2007,
    yearEnd: 2013,
    transponderType: "Honda G",
    chipType: JSON.stringify(["G8D", "ID46", "PCF7936"]),
    compatibleParts: JSON.stringify(["35118-STX-A50", "35118-STX-A51"]),
    frequency: "315 MHz",
    notes: "Mid-generation system",
    dualSystem: false,
  },
  {
    id: "ACURA-RDX-2013-2018",
    make: "ACURA",
    model: "RDX",
    yearStart: 2013,
    yearEnd: 2018,
    transponderType: "Honda G",
    chipType: JSON.stringify(["G8D", "ID46", "PCF7952"]),
    compatibleParts: JSON.stringify(["35118-TX4-A01", "35118-TX4-A02"]),
    frequency: "433.92 MHz",
    notes: "Latest generation system",
    dualSystem: false,
  },
  {
    id: "ACURA-ILX-2019",
    make: "ACURA",
    model: "ILX",
    yearStart: 2019,
    yearEnd: null,
    transponderType: "Honda H",
    chipType: JSON.stringify(["H-Chip", "ID47", "HITAG 3"]),
    compatibleParts: JSON.stringify(["35118-TWA-A01", "35118-TWA-A02"]),
    frequency: "433.92 MHz",
    notes: "Smart key system",
    dualSystem: false,
  },
];
