export const acuraTransponderData = [
  {
    make: "Acura",
    model: "TLX",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "HON66"],
    compatibleParts: ["ACUX", "ACUEX"],
    frequency: "433 MHz",
    notes: "Acura TLX smart key system",
    dualSystem: false,
  },
  {
    make: "Acura",
    model: "MDX",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID47", "HON68"],
    compatibleParts: ["ACUX2", "ACUEX2"],
    frequency: "433 MHz",
    notes: "Acura MDX smart key system",
    dualSystem: false,
  },
  {
    make: "Acura",
    model: "RDX",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID46", "HON66"],
    compatibleParts: ["ACUX", "ACUEX"],
    frequency: "433 MHz",
    notes: "Acura RDX smart key system",
    dualSystem: false,
  },
];
