export const audiTransponderData = [
  {
    make: "Audi",
    model: "A4",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID48", "4D48"],
    compatibleParts: ["AUDX", "AUDEX"],
    frequency: "433 MHz",
    notes: "Audi A4 smart key system",
    dualSystem: false,
  },
  {
    make: "Audi",
    model: "Q5",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "4D47"],
    compatibleParts: ["AUDX2", "AUDEX2"],
    frequency: "433 MHz",
    notes: "Audi Q5 smart key system",
    dualSystem: false,
  },
  {
    make: "Audi",
    model: "A6",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID48", "4D48"],
    compatibleParts: ["AUDX", "AUDEX"],
    frequency: "433 MHz",
    notes: "Audi A6 smart key system",
    dualSystem: false,
  },
];
