export const bmwTransponderData = [
  {
    make: "BMW",
    model: "3 Series",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX", "BMWEX"],
    frequency: "433 MHz",
    notes: "BMW 3 Series smart key system (G20/G21)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "5 Series",
    yearStart: 2017,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX2", "BMWEX2"],
    frequency: "433 MHz",
    notes: "BMW 5 Series smart key system (G30/G31)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "X5",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX3", "BMWEX3"],
    frequency: "433 MHz",
    notes: "BMW X5 smart key system (G05)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "X3",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX4", "BMWEX4"],
    frequency: "433 MHz",
    notes: "BMW X3 smart key system (G01)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "X7",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX5", "BMWEX5"],
    frequency: "433 MHz",
    notes: "BMW X7 smart key system (G07)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "7 Series",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX6", "BMWEX6"],
    frequency: "433 MHz",
    notes: "BMW 7 Series smart key system (G11/G12)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "X1",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX7", "BMWEX7"],
    frequency: "433 MHz",
    notes: "BMW X1 smart key system (F48)",
    dualSystem: false,
  },
  {
    make: "BMW",
    model: "X6",
    yearStart: 2020,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX8", "BMWEX8"],
    frequency: "433 MHz",
    notes: "BMW X6 smart key system (G06)",
    dualSystem: false,
  },
];
