export const buickTransponderData = [
  {
    make: "Buick",
    model: "Encore",
    yearStart: 2013,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "BUI66", "ID33"],
    compatibleParts: ["BUI1", "BUIE1"],
    frequency: "315 MHz",
    notes: "Buick Encore smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Buick",
    model: "Envision",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "BUI66", "ID33"],
    compatibleParts: ["BUI2", "BUIE2"],
    frequency: "315 MHz",
    notes: "Buick Envision smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Buick",
    model: "Enclave",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "BUI66", "ID33"],
    compatibleParts: ["BUI3", "BUIE3"],
    frequency: "315 MHz",
    notes: "Buick Enclave smart key system (2nd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Buick",
    model: "Regal",
    yearStart: 2018,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "BUI66", "ID33"],
    compatibleParts: ["BUI4", "BUIE4"],
    frequency: "315 MHz",
    notes: "Buick Regal smart key system (5th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Buick",
    model: "LaCrosse",
    yearStart: 2017,
    yearEnd: 2019,
    transponderType: "Smart Key",
    chipType: ["ID46", "BUI66", "ID33"],
    compatibleParts: ["BUI5", "BUIE5"],
    frequency: "315 MHz",
    notes: "Buick LaCrosse smart key system (3rd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Buick",
    model: "Cascada",
    yearStart: 2016,
    yearEnd: 2019,
    transponderType: "Smart Key",
    chipType: ["ID46", "BUI66", "ID33"],
    compatibleParts: ["BUI6", "BUIE6"],
    frequency: "315 MHz",
    notes: "Buick Cascada smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Buick",
    model: "Verano",
    yearStart: 2012,
    yearEnd: 2017,
    transponderType: "Transponder Key",
    chipType: ["ID44", "BUI44"],
    compatibleParts: ["BUI7", "BUIE7"],
    frequency: "315 MHz",
    notes: "Buick Verano transponder key system (1st gen)",
    dualSystem: false,
  },
];
