import { TransponderData } from "@/app/services/transponderService";

export const buickTransponderData: TransponderData[] = [
  {
    id: "BUICK-ALLURE-2005",
    make: "BUICK",
    model: "ALLURE",
    yearStart: 2005,
    yearEnd: 2009,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "PassKey III system",
    dualSystem: false,
  },
  {
    id: "BUICK-ALLURE-2010",
    make: "BUICK",
    model: "ALLURE",
    yearStart: 2010,
    yearEnd: null,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify([
      "Hitag2",
      "ID46",
      "PCF7936AS",
      "TP12GM",
      "T14",
      "CN3",
      "XT27A66",
      "K-JMD",
    ]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-CASCADA-2016",
    make: "BUICK",
    model: "CASCADA",
    yearStart: 2016,
    yearEnd: 2019,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46", "ID46E", "PCF7937E", "NCF2951E"]),
    compatibleParts: JSON.stringify([
      "13500224",
      "KR55WK50073",
      "13585206",
      "OHT05918179",
    ]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-CENTURY-1997",
    make: "BUICK",
    model: "CENTURY",
    yearStart: 1997,
    yearEnd: 1999,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-CENTURY-2000",
    make: "BUICK",
    model: "CENTURY",
    yearStart: 2000,
    yearEnd: 2005,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-ENCLAVE-2008",
    make: "BUICK",
    model: "ENCLAVE",
    yearStart: 2008,
    yearEnd: 2017,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify([
      "Hitag2",
      "ID46",
      "PCF7936AS",
      "TP12GM",
      "T14",
      "CN3",
      "XT27A66",
      "K-JMD",
    ]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-ENCLAVE-2017",
    make: "BUICK",
    model: "ENCLAVE",
    yearStart: 2017,
    yearEnd: 2020,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7952E", "PCF7961E"]),
    compatibleParts: JSON.stringify([
      "HYQ4EA",
      "13532751",
      "13521090",
      "13506668",
    ]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-ENCORE-2014",
    make: "BUICK",
    model: "ENCORE",
    yearStart: 2014,
    yearEnd: 2020,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7937E", "PCF7941E"]),
    compatibleParts: JSON.stringify([
      "OHT01060512",
      "13504204",
      "13500226",
      "13585814",
    ]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-ENCORE-2017",
    make: "BUICK",
    model: "ENCORE",
    yearStart: 2017,
    yearEnd: 2021,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7952E", "PCF7961E"]),
    compatibleParts: JSON.stringify(["HYQ4AA", "13506665", "13532383"]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-ENVISION-2016",
    make: "BUICK",
    model: "ENVISION",
    yearStart: 2016,
    yearEnd: 2020,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7952E", "PCF7961E"]),
    compatibleParts: JSON.stringify([
      "HYQ4AA",
      "13532385",
      "13508406",
      "13584500",
    ]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-LACROSSE-2005",
    make: "BUICK",
    model: "LACROSSE",
    yearStart: 2005,
    yearEnd: 2009,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-LACROSSE-2010",
    make: "BUICK",
    model: "LACROSSE",
    yearStart: 2010,
    yearEnd: 2016,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7937E", "NCF2951E"]),
    compatibleParts: JSON.stringify([
      "V2T01060512",
      "13585811",
      "13576144",
      "5912555",
    ]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-LACROSSE-2017",
    make: "BUICK",
    model: "LACROSSE",
    yearStart: 2017,
    yearEnd: 2019,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7952E", "PCF7961E"]),
    compatibleParts: JSON.stringify(["HYQ4EA", "13508414"]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-LESABRE-1992",
    make: "BUICK",
    model: "LESABRE",
    yearStart: 1992,
    yearEnd: 1999,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-LESABRE-2000",
    make: "BUICK",
    model: "LESABRE",
    yearStart: 2000,
    yearEnd: 2005,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-LUCERNE-2006",
    make: "BUICK",
    model: "LUCERNE",
    yearStart: 2006,
    yearEnd: 2011,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify([
      "Hitag2",
      "ID46",
      "PCF7936AS",
      "TP12GM",
      "T14",
      "CN3",
      "XT27A66",
      "K-JMD",
    ]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-PARK-AVENUE-1991",
    make: "BUICK",
    model: "PARK AVENUE",
    yearStart: 1991,
    yearEnd: 1996,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-PARK-AVENUE-1997",
    make: "BUICK",
    model: "PARK AVENUE",
    yearStart: 1997,
    yearEnd: 2005,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "PassKey III system",
    dualSystem: false,
  },
  {
    id: "BUICK-RAINIER-2004",
    make: "BUICK",
    model: "RAINIER",
    yearStart: 2004,
    yearEnd: 2007,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "PassKey III system",
    dualSystem: false,
  },
  {
    id: "BUICK-REATTA-1990",
    make: "BUICK",
    model: "REATTA",
    yearStart: 1990,
    yearEnd: 1992,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-REGAL-1994",
    make: "BUICK",
    model: "REGAL",
    yearStart: 1994,
    yearEnd: 2004,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-REGAL-2011",
    make: "BUICK",
    model: "REGAL",
    yearStart: 2011,
    yearEnd: 2017,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7937E", "PCF7941E"]),
    compatibleParts: JSON.stringify(["13504200", "13504258", "13504205"]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-REGAL-2018",
    make: "BUICK",
    model: "REGAL",
    yearStart: 2018,
    yearEnd: 2020,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7952E", "PCF7961E"]),
    compatibleParts: JSON.stringify(["HYQ4EA", "13511629"]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
  {
    id: "BUICK-RENDEVOUZ-2002",
    make: "BUICK",
    model: "RENDEVOUZ",
    yearStart: 2002,
    yearEnd: 2007,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "PassKey III system",
    dualSystem: false,
  },
  {
    id: "BUICK-RIVIERA-1990",
    make: "BUICK",
    model: "RIVIERA",
    yearStart: 1990,
    yearEnd: 1998,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-ROADMASTER-1994",
    make: "BUICK",
    model: "ROADMASTER",
    yearStart: 1994,
    yearEnd: 1996,
    transponderType: "VATS",
    chipType: JSON.stringify(["PassKey"]),
    compatibleParts: JSON.stringify([]),
    frequency: null,
    notes: "PassKey Anti Theft System",
    dualSystem: false,
  },
  {
    id: "BUICK-TERRAZA-2005",
    make: "BUICK",
    model: "TERRAZA",
    yearStart: 2005,
    yearEnd: 2007,
    transponderType: "MEGAMOS 13",
    chipType: JSON.stringify(["ID13", "Silca 13", "JMA TP05"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "PassKey III system",
    dualSystem: false,
  },
  {
    id: "BUICK-VERANO-2012",
    make: "BUICK",
    model: "VERANO",
    yearStart: 2012,
    yearEnd: 2017,
    transponderType: "Hitag2 Extended",
    chipType: JSON.stringify(["ID46E", "PCF7937E", "PCF7941E"]),
    compatibleParts: JSON.stringify([
      "13500227",
      "13504205",
      "13585811",
      "13576144",
    ]),
    frequency: "433.92 MHz",
    notes: null,
    dualSystem: false,
  },
];
