import { TransponderData } from "@/app/services/transponderService";

export const chevroletTransponderData: TransponderData[] = [
  {
    id: "CHEVROLET-SILVERADO-2007-2013",
    make: "CHEVROLET",
    model: "SILVERADO",
    yearStart: 2007,
    yearEnd: 2013,
    transponderType: "PK3+",
    chipType: JSON.stringify(["ID46", "PCF7936"]),
    compatibleParts: JSON.stringify(["13500219", "13500220"]),
    frequency: "315 MHz",
    notes: "First generation transponder system",
    dualSystem: false,
  },
  {
    id: "CHEVROLET-CRUZE-2011-2015",
    make: "CHEVROLET",
    model: "CRUZE",
    yearStart: 2011,
    yearEnd: 2015,
    transponderType: "PK3+",
    chipType: JSON.stringify(["ID46", "PCF7936"]),
    compatibleParts: JSON.stringify(["13504749", "13504750"]),
    frequency: "315 MHz",
    notes: "Mid-generation system",
    dualSystem: false,
  },
  {
    id: "CHEVROLET-MALIBU-2016-2019",
    make: "CHEVROLET",
    model: "MALIBU",
    yearStart: 2016,
    yearEnd: 2019,
    transponderType: "HITAG 3",
    chipType: JSON.stringify(["ID47", "PCF7953"]),
    compatibleParts: JSON.stringify(["13508771", "13508772"]),
    frequency: "433.92 MHz",
    notes: "Latest generation system",
    dualSystem: false,
  },
  {
    id: "CHEVROLET-CAMARO-2020",
    make: "CHEVROLET",
    model: "CAMARO",
    yearStart: 2020,
    yearEnd: null,
    transponderType: "HITAG AES",
    chipType: JSON.stringify(["ID49", "PCF7953M"]),
    compatibleParts: JSON.stringify(["13529841", "13529842"]),
    frequency: "433.92 MHz",
    notes: "Smart key system",
    dualSystem: false,
  },
];

module.exports = { chevroletTransponderData };
