export const chevroletTransponderData = [
  {
    make: "Chevrolet",
    model: "Malibu",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "GM66"],
    compatibleParts: ["CHEVX", "CHEVEX"],
    frequency: "315 MHz",
    notes: "Chevrolet Malibu smart key system",
    dualSystem: false,
  },
  {
    make: "Chevrolet",
    model: "Equinox",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "GM68"],
    compatibleParts: ["CHEVX2", "CHEVEX2"],
    frequency: "315 MHz",
    notes: "Chevrolet Equinox smart key system",
    dualSystem: false,
  },
  {
    make: "Chevrolet",
    model: "Silverado",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "GM66"],
    compatibleParts: ["CHEVX", "CHEVEX"],
    frequency: "315 MHz",
    notes: "Chevrolet Silverado smart key system",
    dualSystem: false,
  },
];
