export const chryslerTransponderData = [
  {
    make: "Chrysler",
    model: "300",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "CHR66"],
    compatibleParts: ["CHRX", "CHREX"],
    frequency: "315 MHz",
    notes: "Chrysler 300 smart key system",
    dualSystem: false,
  },
  {
    make: "Chrysler",
    model: "Pacifica",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "CHR68"],
    compatibleParts: ["CHRX2", "CHREX2"],
    frequency: "315 MHz",
    notes: "Chrysler Pacifica smart key system",
    dualSystem: false,
  },
  {
    make: "Chrysler",
    model: "Voyager",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "CHR66"],
    compatibleParts: ["CHRX", "CHREX"],
    frequency: "315 MHz",
    notes: "Chrysler Voyager smart key system",
    dualSystem: false,
  },
];
