export const dodgeTransponderData = [
  {
    make: "Dodge",
    model: "Charger",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "DOD66", "ID33"],
    compatibleParts: ["DOD1", "DODE1"],
    frequency: "315 MHz",
    notes: "Dodge Charger smart key system (7th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Dodge",
    model: "Challenger",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "DOD66", "ID33"],
    compatibleParts: ["DOD2", "DODE2"],
    frequency: "315 MHz",
    notes:
      "Dodge Challenger smart key system (3rd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Dodge",
    model: "Durango",
    yearStart: 2011,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "DOD66", "ID33"],
    compatibleParts: ["DOD3", "DODE3"],
    frequency: "315 MHz",
    notes: "Dodge Durango smart key system (2nd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Dodge",
    model: "Grand Caravan",
    yearStart: 2008,
    yearEnd: 2020,
    transponderType: "Transponder Key",
    chipType: ["ID44", "DOD44"],
    compatibleParts: ["DOD4", "DODE4"],
    frequency: "315 MHz",
    notes: "Dodge Grand Caravan transponder key system (5th gen)",
    dualSystem: false,
  },
  {
    make: "Dodge",
    model: "Journey",
    yearStart: 2009,
    yearEnd: 2020,
    transponderType: "Transponder Key",
    chipType: ["ID44", "DOD44"],
    compatibleParts: ["DOD5", "DODE5"],
    frequency: "315 MHz",
    notes: "Dodge Journey transponder key system (1st gen)",
    dualSystem: false,
  },
  {
    make: "Dodge",
    model: "Dart",
    yearStart: 2013,
    yearEnd: 2016,
    transponderType: "Transponder Key",
    chipType: ["ID46", "DOD66"],
    compatibleParts: ["DOD6", "DODE6"],
    frequency: "315 MHz",
    notes: "Dodge Dart transponder key system (1st gen)",
    dualSystem: false,
  },
  {
    make: "Dodge",
    model: "Ram 1500",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "DOD66", "ID33"],
    compatibleParts: ["DOD7", "DODE7"],
    frequency: "315 MHz",
    notes: "Dodge Ram 1500 smart key system (5th gen) with backup transponder",
    dualSystem: true,
  },
];
