export const fiatTransponderData = [
  {
    make: "Fiat",
    model: "500",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "FIA66"],
    compatibleParts: ["FIAX", "FIAEX"],
    frequency: "433 MHz",
    notes: "Fiat 500 smart key system",
    dualSystem: false,
  },
  {
    make: "Fiat",
    model: "500X",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "FIA68"],
    compatibleParts: ["FIAX2", "FIAEX2"],
    frequency: "433 MHz",
    notes: "Fiat 500X smart key system",
    dualSystem: false,
  },
  {
    make: "Fiat",
    model: "124 Spider",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "FIA66"],
    compatibleParts: ["FIAX", "FIAEX"],
    frequency: "433 MHz",
    notes: "Fiat 124 Spider smart key system",
    dualSystem: false,
  },
];
