import { TransponderData } from "@/app/services/transponderService";

export const fordTransponderData: TransponderData[] = [
  {
    id: "FORD-F150-2009-2014",
    make: "FORD",
    model: "F-150",
    yearStart: 2009,
    yearEnd: 2014,
    transponderType: "Texas 4D-63 80-bit",
    chipType: JSON.stringify(["4D63", "TPMS"]),
    compatibleParts: JSON.stringify(["164-R8073", "164-R8074"]),
    frequency: "315 MHz",
    notes: "Standard key with integrated TPMS",
    dualSystem: false,
  },
  {
    id: "FORD-MUSTANG-2015-2019",
    make: "FORD",
    model: "MUSTANG",
    yearStart: 2015,
    yearEnd: 2019,
    transponderType: "Texas 80-bit",
    chipType: JSON.stringify(["4D63", "H-chip"]),
    compatibleParts: JSON.stringify(["164-R8995", "164-R8996"]),
    frequency: "315 MHz",
    notes: "Smart key system",
    dualSystem: true,
  },
  {
    id: "FORD-EXPLORER-2020",
    make: "FORD",
    model: "EXPLORER",
    yearStart: 2020,
    yearEnd: null,
    transponderType: "Texas Pro",
    chipType: JSON.stringify(["4D83", "H-chip Pro"]),
    compatibleParts: JSON.stringify(["164-R9995", "164-R9996"]),
    frequency: "433.92 MHz",
    notes: "Latest generation smart key",
    dualSystem: true,
  },
  {
    id: "FORD-ESCAPE-2013-2019",
    make: "FORD",
    model: "ESCAPE",
    yearStart: 2013,
    yearEnd: 2019,
    transponderType: "Texas 4D-63 80-bit",
    chipType: JSON.stringify(["4D63", "TPMS"]),
    compatibleParts: JSON.stringify(["164-R8133", "164-R8134"]),
    frequency: "315 MHz",
    notes: "Standard key with PEPS",
    dualSystem: false,
  },
];
