export const fordTransponderData = [
  {
    make: "Ford",
    model: "F-150",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "FORD66"],
    compatibleParts: ["FORDX", "FORDEX"],
    frequency: "315 MHz",
    notes: "Ford F-150 smart key system",
    dualSystem: false,
  },
  {
    make: "Ford",
    model: "Explorer",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID47", "FORD68"],
    compatibleParts: ["FORDX2", "FORDEX2"],
    frequency: "315 MHz",
    notes: "Ford Explorer smart key system",
    dualSystem: false,
  },
  {
    make: "Ford",
    model: "Escape",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID46", "FORD66"],
    compatibleParts: ["FORDX", "FORDEX"],
    frequency: "315 MHz",
    notes: "Ford Escape smart key system",
    dualSystem: false,
  },
];
