import { TransponderData } from "@/app/services/transponderService";

export const hondaTransponderData: TransponderData[] = [
  {
    id: "HONDA-CIVIC-2006-2011",
    make: "HONDA",
    model: "CIVIC",
    yearStart: 2006,
    yearEnd: 2011,
    transponderType: "Honda G",
    chipType: JSON.stringify(["G-chip", "ID46"]),
    compatibleParts: JSON.stringify(["35111-SNE-A01", "35111-SNE-A02"]),
    frequency: "315 MHz",
    notes: "8th generation Civic",
    dualSystem: false,
  },
  {
    id: "HONDA-ACCORD-2013-2017",
    make: "HONDA",
    model: "ACCORD",
    yearStart: 2013,
    yearEnd: 2017,
    transponderType: "Honda G",
    chipType: JSON.stringify(["G-chip", "ID46"]),
    compatibleParts: JSON.stringify(["35118-T2A-A20", "35118-T2A-A21"]),
    frequency: "433.92 MHz",
    notes: "9th generation Accord",
    dualSystem: false,
  },
  {
    id: "HONDA-CRV-2017-2022",
    make: "HONDA",
    model: "CR-V",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Honda H",
    chipType: JSON.stringify(["H-chip", "ID47"]),
    compatibleParts: JSON.stringify(["35118-TLA-A20", "35118-TLA-A21"]),
    frequency: "433.92 MHz",
    notes: "5th generation CR-V",
    dualSystem: true,
  },
  {
    id: "HONDA-PILOT-2019",
    make: "HONDA",
    model: "PILOT",
    yearStart: 2019,
    yearEnd: null,
    transponderType: "Honda H",
    chipType: JSON.stringify(["H-chip", "ID47"]),
    compatibleParts: JSON.stringify(["35118-TG7-A21", "35118-TG7-A22"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with smart entry",
    dualSystem: true,
  },
];
