export const hondaTransponderData = [
  {
    make: "Honda",
    model: "Civic",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "HON66"],
    compatibleParts: ["HONDX", "HONEX"],
    frequency: "433 MHz",
    notes: "Honda Civic smart key system (10th/11th gen)",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "Accord",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID47", "HON68"],
    compatibleParts: ["HONDAX", "HONEX2"],
    frequency: "433 MHz",
    notes: "Honda Accord smart key system (10th gen)",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "CR-V",
    yearStart: 2017,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "HON66"],
    compatibleParts: ["HONDX", "HONEX"],
    frequency: "433 MHz",
    notes: "Honda CR-V smart key system (5th gen)",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "Pilot",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID47", "HON68"],
    compatibleParts: ["HONDAX", "HONEX2"],
    frequency: "433 MHz",
    notes: "Honda Pilot smart key system (3rd gen)",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "HR-V",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "HON66"],
    compatibleParts: ["HONDX3", "HONEX3"],
    frequency: "433 MHz",
    notes: "Honda HR-V smart key system (2nd gen)",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "Odyssey",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID47", "HON68"],
    compatibleParts: ["HONDAX4", "HONEX4"],
    frequency: "433 MHz",
    notes: "Honda Odyssey smart key system (5th gen)",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "Passport",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "HON66"],
    compatibleParts: ["HONDX5", "HONEX5"],
    frequency: "433 MHz",
    notes: "Honda Passport smart key system",
    dualSystem: false,
  },
  {
    make: "Honda",
    model: "Ridgeline",
    yearStart: 2017,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID47", "HON68"],
    compatibleParts: ["HONDAX6", "HONEX6"],
    frequency: "433 MHz",
    notes: "Honda Ridgeline smart key system (2nd gen)",
    dualSystem: false,
  },
];
