export const hyundaiTransponderData = [
  {
    make: "Hyundai",
    model: "Elantra",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "HYN66"],
    compatibleParts: ["HYNX", "HYNEX"],
    frequency: "315 MHz",
    notes: "Hyundai Elantra smart key system",
    dualSystem: false,
  },
  {
    make: "Hyundai",
    model: "Tucson",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "HYN68"],
    compatibleParts: ["HYNX2", "HYNEX2"],
    frequency: "315 MHz",
    notes: "Hyundai Tucson smart key system",
    dualSystem: false,
  },
  {
    make: "Hyundai",
    model: "Sonata",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "HYN66"],
    compatibleParts: ["HYNX", "HYNEX"],
    frequency: "315 MHz",
    notes: "Hyundai Sonata smart key system",
    dualSystem: false,
  },
];
