export const isuzuTransponderData = [
  {
    make: "Isuzu",
    model: "D-Max",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "ISU66"],
    compatibleParts: ["ISUX", "ISUEX"],
    frequency: "315 MHz",
    notes: "Isuzu D-Max smart key system",
    dualSystem: false,
  },
  {
    make: "Isuzu",
    model: "MU-X",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "ISU68"],
    compatibleParts: ["ISUX2", "ISUEX2"],
    frequency: "315 MHz",
    notes: "Isuzu MU-X smart key system",
    dualSystem: false,
  },
  {
    make: "Isuzu",
    model: "Rodeo",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "ISU66"],
    compatibleParts: ["ISUX", "ISUEX"],
    frequency: "315 MHz",
    notes: "Isuzu Rodeo smart key system",
    dualSystem: false,
  },
];
