export const kiaTransponderData = [
  {
    make: "Kia",
    model: "Forte",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "KIA66"],
    compatibleParts: ["KIAX", "KIAEX"],
    frequency: "315 MHz",
    notes: "Kia Forte smart key system",
    dualSystem: false,
  },
  {
    make: "Kia",
    model: "Sportage",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "KIA68"],
    compatibleParts: ["KIAX2", "KIAEX2"],
    frequency: "315 MHz",
    notes: "Kia Sportage smart key system",
    dualSystem: false,
  },
  {
    make: "Kia",
    model: "Optima",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "KIA66"],
    compatibleParts: ["KIAX", "KIAEX"],
    frequency: "315 MHz",
    notes: "Kia Optima smart key system",
    dualSystem: false,
  },
];
