import { TransponderData } from "@/app/services/transponderService";

export const landRoverTransponderData: TransponderData[] = [
  // Defender
  {
    id: "LANDROVER-DEFENDER-1999-2003",
    make: "LAND ROVER",
    model: "DEFENDER",
    yearStart: 1999,
    yearEnd: 2003,
    transponderType: "Philips Crypto",
    chipType: JSON.stringify(["PCF7935", "Silca T15", "JMA TP14"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "First generation Defender with Philips Crypto",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DEFENDER-2003-2006",
    make: "LAND ROVER",
    model: "DEFENDER",
    yearStart: 2003,
    yearEnd: 2006,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7936", "JMA TP12", "CN3"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Updated to Philips Crypto 2 system",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DEFENDER-2006-2013",
    make: "LAND ROVER",
    model: "DEFENDER",
    yearStart: 2006,
    yearEnd: 2013,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7936", "PCF7945"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Updated transponder system",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DEFENDER-2014-2016",
    make: "LAND ROVER",
    model: "DEFENDER",
    yearStart: 2014,
    yearEnd: 2016,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify([
      "5E0U30427",
      "DH12-15K601-BC",
      "LR087107",
      "LR087665",
    ]),
    frequency: "125 kHz",
    notes: "Final generation Defender with Hitag Pro",
    dualSystem: false,
  },

  // Discovery
  {
    id: "LANDROVER-DISCOVERY-1995-1998",
    make: "LAND ROVER",
    model: "DISCOVERY",
    yearStart: 1995,
    yearEnd: 1998,
    transponderType: "Philips 33",
    chipType: JSON.stringify([
      "ID33",
      "PCF7930",
      "PCF7931",
      "JMA TP01",
      "JMA TP05",
    ]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "First generation Discovery",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DISCOVERY-1999-2004",
    make: "LAND ROVER",
    model: "DISCOVERY",
    yearStart: 1999,
    yearEnd: 2004,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7936", "ID44", "PCF7935"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Second generation Discovery",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DISCOVERY-2005-2009",
    make: "LAND ROVER",
    model: "DISCOVERY",
    yearStart: 2005,
    yearEnd: 2009,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7936", "PCF7941"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Third generation Discovery",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DISCOVERY-2009-2011",
    make: "LAND ROVER",
    model: "DISCOVERY",
    yearStart: 2009,
    yearEnd: 2011,
    transponderType: "Hitag 2",
    chipType: JSON.stringify(["ID46", "NXP PCF7953A", "PCF7953AT"]),
    compatibleParts: JSON.stringify(["LR020366", "LR032796"]),
    frequency: "125 kHz",
    notes: "Updated transponder system",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DISCOVERY-2010-2017",
    make: "LAND ROVER",
    model: "DISCOVERY",
    yearStart: 2010,
    yearEnd: 2017,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify(["LR087661", "LR087663", "5E0U30277"]),
    frequency: "125 kHz",
    notes: "Fourth generation Discovery",
    dualSystem: false,
  },
  {
    id: "LANDROVER-DISCOVERY-2017-2021",
    make: "LAND ROVER",
    model: "DISCOVERY",
    yearStart: 2017,
    yearEnd: 2021,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify([
      "5AVC11F08",
      "LR116874",
      "5AVC13F08",
      "JK52-15K601-BG",
    ]),
    frequency: "125 kHz",
    notes: "Fifth generation Discovery",
    dualSystem: false,
  },

  // Range Rover Evoque
  {
    id: "LANDROVER-EVOQUE-2011-2018",
    make: "LAND ROVER",
    model: "RANGE ROVER EVOQUE",
    yearStart: 2011,
    yearEnd: 2018,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify([
      "BJ32-15K601-DE",
      "5E0U40457",
      "LR087106",
    ]),
    frequency: "125 kHz",
    notes: "First generation Evoque",
    dualSystem: false,
  },
  {
    id: "LANDROVER-EVOQUE-2018-2021",
    make: "LAND ROVER",
    model: "RANGE ROVER EVOQUE",
    yearStart: 2018,
    yearEnd: 2021,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify([
      "JK52-15K601-BG",
      "LR116874",
      "5AVC11F08",
      "LR116871",
    ]),
    frequency: "125 kHz",
    notes: "Second generation Evoque",
    dualSystem: false,
  },

  // Freelander
  {
    id: "LANDROVER-FREELANDER-2000-2003",
    make: "LAND ROVER",
    model: "FREELANDER",
    yearStart: 2000,
    yearEnd: 2003,
    transponderType: "Philips Crypto",
    chipType: JSON.stringify(["PCF7935", "Silca T15", "JMA TP14"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "First generation Freelander",
    dualSystem: false,
  },
  {
    id: "LANDROVER-FREELANDER-2003-2006",
    make: "LAND ROVER",
    model: "FREELANDER",
    yearStart: 2003,
    yearEnd: 2006,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7936", "Silca T14"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Updated transponder system",
    dualSystem: false,
  },
  {
    id: "LANDROVER-FREELANDER-2007-2012",
    make: "LAND ROVER",
    model: "FREELANDER",
    yearStart: 2007,
    yearEnd: 2012,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7945"]),
    compatibleParts: JSON.stringify([
      "6H52-15K601-AG",
      "LR013005",
      "LR001863",
      "LR006170",
    ]),
    frequency: "125 kHz",
    notes: "Second generation Freelander",
    dualSystem: false,
  },
  {
    id: "LANDROVER-FREELANDER-2011-2014",
    make: "LAND ROVER",
    model: "FREELANDER",
    yearStart: 2011,
    yearEnd: 2014,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify([
      "LR087663",
      "CH22-15K601-BD",
      "CH22-15K601-BF",
    ]),
    frequency: "125 kHz",
    notes: "Updated transponder system",
    dualSystem: false,
  },

  // Range Rover
  {
    id: "LANDROVER-RANGEROVER-1996-2002",
    make: "LAND ROVER",
    model: "RANGE ROVER",
    yearStart: 1996,
    yearEnd: 2002,
    transponderType: "Philips Crypto",
    chipType: JSON.stringify(["PCF7935", "Silca T15", "JMA TP14"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "First generation Range Rover",
    dualSystem: false,
  },
  {
    id: "LANDROVER-RANGEROVER-2002-2009",
    make: "LAND ROVER",
    model: "RANGE ROVER",
    yearStart: 2002,
    yearEnd: 2009,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "Hitag2", "PCF7936", "JMA TP12", "CN3"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Second generation Range Rover",
    dualSystem: false,
  },
  {
    id: "LANDROVER-RANGEROVER-2009-2012",
    make: "LAND ROVER",
    model: "RANGE ROVER",
    yearStart: 2009,
    yearEnd: 2012,
    transponderType: "Hitag 2",
    chipType: JSON.stringify(["ID46", "NXP PCF7953A", "PCF7953AT"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Updated transponder system",
    dualSystem: false,
  },
  {
    id: "LANDROVER-RANGEROVER-2012-2016",
    make: "LAND ROVER",
    model: "RANGE ROVER",
    yearStart: 2012,
    yearEnd: 2016,
    transponderType: "Hitag Pro",
    chipType: JSON.stringify(["PCF7953P", "ID49", "ID47"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Fourth generation Range Rover",
    dualSystem: false,
  },
];
