export const landRoverTransponderData = [
  {
    make: "Land Rover",
    model: "Range Rover",
    yearStart: 2013,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR1", "LRRE1"],
    frequency: "315 MHz",
    notes: "Range Rover smart key system (4th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Land Rover",
    model: "Range Rover Sport",
    yearStart: 2014,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR2", "LRRE2"],
    frequency: "315 MHz",
    notes:
      "Range Rover Sport smart key system (2nd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Land Rover",
    model: "Range Rover Evoque",
    yearStart: 2012,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR3", "LRRE3"],
    frequency: "315 MHz",
    notes:
      "Range Rover Evoque smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Land Rover",
    model: "Range Rover Velar",
    yearStart: 2017,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR4", "LRRE4"],
    frequency: "315 MHz",
    notes:
      "Range Rover Velar smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Land Rover",
    model: "Defender",
    yearStart: 2020,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR5", "LRRE5"],
    frequency: "315 MHz",
    notes: "Defender smart key system (new gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Land Rover",
    model: "Discovery",
    yearStart: 2017,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR6", "LRRE6"],
    frequency: "315 MHz",
    notes: "Discovery smart key system (5th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Land Rover",
    model: "Discovery Sport",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LRR66", "ID33"],
    compatibleParts: ["LRR7", "LRRE7"],
    frequency: "315 MHz",
    notes: "Discovery Sport smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
];
