export const lexusTransponderData = [
  {
    make: "Lexus",
    model: "ES",
    yearStart: 2013,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX1", "LEXE1"],
    frequency: "315 MHz",
    notes: "Lexus ES smart key system (6th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "RX",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX2", "LEXE2"],
    frequency: "315 MHz",
    notes: "Lexus RX smart key system (4th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "NX",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX3", "LEXE3"],
    frequency: "315 MHz",
    notes: "Lexus NX smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "IS",
    yearStart: 2014,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX4", "LEXE4"],
    frequency: "315 MHz",
    notes: "Lexus IS smart key system (3rd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "GX",
    yearStart: 2010,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX5", "LEXE5"],
    frequency: "315 MHz",
    notes: "Lexus GX smart key system (2nd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "UX",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX6", "LEXE6"],
    frequency: "315 MHz",
    notes: "Lexus UX smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "LC",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX7", "LEXE7"],
    frequency: "315 MHz",
    notes: "Lexus LC smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Lexus",
    model: "LS",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "LEX66", "ID33"],
    compatibleParts: ["LEX8", "LEXE8"],
    frequency: "315 MHz",
    notes: "Lexus LS smart key system (5th gen) with backup transponder",
    dualSystem: true,
  },
];
