import { TransponderData } from "@/app/services/transponderService";

export const nissanTransponderData: TransponderData[] = [
  {
    id: "NISSAN-ALTIMA-2007-2012",
    make: "NISSAN",
    model: "ALTIMA",
    yearStart: 2007,
    yearEnd: 2012,
    transponderType: "Texas Crypto",
    chipType: JSON.stringify(["ID46", "PCF7936"]),
    compatibleParts: JSON.stringify(["28268-JA000", "28268-JA001"]),
    frequency: "315 MHz",
    notes: "L32 generation with intelligent key",
    dualSystem: false,
  },
  {
    id: "NISSAN-ROGUE-2014-2020",
    make: "NISSAN",
    model: "ROGUE",
    yearStart: 2014,
    yearEnd: 2020,
    transponderType: "Texas DST80",
    chipType: JSON.stringify(["ID47", "DST80"]),
    compatibleParts: JSON.stringify(["28268-4BA0A", "28268-4BA1A"]),
    frequency: "433.92 MHz",
    notes: "T32 generation with intelligent key",
    dualSystem: true,
  },
  {
    id: "NISSAN-MAXIMA-2016-2021",
    make: "NISSAN",
    model: "MAXIMA",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Texas DST80",
    chipType: JSON.stringify(["ID47", "DST80"]),
    compatibleParts: JSON.stringify(["28268-9HS0A", "28268-9HS1A"]),
    frequency: "433.92 MHz",
    notes: "A36 generation with intelligent key",
    dualSystem: true,
  },
  {
    id: "NISSAN-SENTRA-2020",
    make: "NISSAN",
    model: "SENTRA",
    yearStart: 2020,
    yearEnd: null,
    transponderType: "Texas DST AES",
    chipType: JSON.stringify(["ID4D-80", "DST AES"]),
    compatibleParts: JSON.stringify(["28268-5SA0A", "28268-5SA1A"]),
    frequency: "433.92 MHz",
    notes: "B18 generation with intelligent key",
    dualSystem: true,
  },
];
