export const nissanTransponderData = [
  {
    make: "Nissan",
    model: "Altima",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "NIS66"],
    compatibleParts: ["NISX", "NISEX"],
    frequency: "315 MHz",
    notes: "Nissan Altima smart key system",
    dualSystem: false,
  },
  {
    make: "Nissan",
    model: "Rogue",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "NIS68"],
    compatibleParts: ["NISX2", "NISEX2"],
    frequency: "315 MHz",
    notes: "Nissan Rogue smart key system",
    dualSystem: false,
  },
  {
    make: "Nissan",
    model: "Maxima",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "NIS66"],
    compatibleParts: ["NISX", "NISEX"],
    frequency: "315 MHz",
    notes: "Nissan Maxima smart key system",
    dualSystem: false,
  },
];
