export const peugeotTransponderData = [
  {
    make: "Peugeot",
    model: "208",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "PEU66"],
    compatibleParts: ["PEUX", "PEUEX"],
    frequency: "433 MHz",
    notes: "Peugeot 208 smart key system",
    dualSystem: false,
  },
  {
    make: "Peugeot",
    model: "3008",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "PEU68"],
    compatibleParts: ["PEUX2", "PEUEX2"],
    frequency: "433 MHz",
    notes: "Peugeot 3008 smart key system",
    dualSystem: false,
  },
  {
    make: "Peugeot",
    model: "508",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "PEU66"],
    compatibleParts: ["PEUX", "PEUEX"],
    frequency: "433 MHz",
    notes: "Peugeot 508 smart key system",
    dualSystem: false,
  },
];
