import { TransponderData } from "@/app/services/transponderService";

export const peugeotTransponderData: TransponderData[] = [
  {
    id: "PEUGEOT-3008-2017",
    make: "PEUGEOT",
    model: "3008",
    yearStart: 2017,
    yearEnd: null,
    transponderType: "Hitag AES",
    chipType: JSON.stringify(["ID4A", "PCF7953M"]),
    compatibleParts: JSON.stringify(["98105588ZD", "98124195ZD"]),
    frequency: "433.92 MHz",
    notes: "Latest generation transponder system",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-106-1996",
    make: "PEUGEOT",
    model: "106",
    yearStart: 1996,
    yearEnd: 2000,
    transponderType: "Philips 33",
    chipType: JSON.stringify([
      "ID33",
      "PCF7930",
      "PCF7931",
      "JMA TP05",
      "Silca T1",
    ]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "First generation transponder system",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-308-2007",
    make: "PEUGEOT",
    model: "308",
    yearStart: 2007,
    yearEnd: 2012,
    transponderType: "Hitag2",
    chipType: JSON.stringify([
      "ID46",
      "PCF7936",
      "JMA TP12",
      "SILCA T14",
      "XT27",
      "K-JMD",
    ]),
    compatibleParts: JSON.stringify(["6490CS", "6490CT"]),
    frequency: "433.92 MHz",
    notes: "PCF7941/PCF7961 transponder compatible",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-BOXER-2007",
    make: "PEUGEOT",
    model: "BOXER",
    yearStart: 2007,
    yearEnd: 2016,
    transponderType: "Hitag2+",
    chipType: JSON.stringify(["ID46", "PCF7946A"]),
    compatibleParts: JSON.stringify(["71752589", "71776161", "6000627330"]),
    frequency: "433.92 MHz",
    notes: "Commercial vehicle system",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-RIFTER-2018",
    make: "PEUGEOT",
    model: "RIFTER",
    yearStart: 2018,
    yearEnd: null,
    transponderType: "Hitag AES",
    chipType: JSON.stringify(["ID4A", "ID51", "PCF7953M"]),
    compatibleParts: JSON.stringify(["98105588ZD", "98124195ZD"]),
    frequency: "433.92 MHz",
    notes: "Latest platform transponder",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-SATELIS-2006",
    make: "PEUGEOT",
    model: "SATELIS",
    yearStart: 2006,
    yearEnd: null,
    transponderType: "Temic 11",
    chipType: JSON.stringify(["ID11", "JMA TP05", "SILCA T5"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Motorcycle/Scooter system",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-SPEEDFIGHT-1997",
    make: "PEUGEOT",
    model: "SPEEDFIGHT",
    yearStart: 1997,
    yearEnd: null,
    transponderType: "Temic 11",
    chipType: JSON.stringify(["ID11", "JMA TP05", "SILCA T5"]),
    compatibleParts: JSON.stringify([]),
    frequency: "125 kHz",
    notes: "Motorcycle/Scooter system",
    dualSystem: false,
  },
  {
    id: "PEUGEOT-206-2000",
    make: "PEUGEOT",
    model: "206",
    yearStart: 2000,
    yearEnd: 2010,
    transponderType: "Philips Crypto 2",
    chipType: JSON.stringify(["ID46", "PCF7936", "TP12"]),
    compatibleParts: JSON.stringify(["VA2", "HU83"]),
    frequency: "433.92 MHz",
    notes: "Mid-generation system",
    dualSystem: false,
  },
];

module.exports = { peugeotTransponderData };
