export const subaruTransponderData = [
  {
    make: "Subaru",
    model: "Outback",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB1", "SUBE1"],
    frequency: "315 MHz",
    notes: "Subaru Outback smart key system (5th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Subaru",
    model: "Forester",
    yearStart: 2014,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB2", "SUBE2"],
    frequency: "315 MHz",
    notes: "Subaru Forester smart key system (4th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Subaru",
    model: "Crosstrek",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB3", "SUBE3"],
    frequency: "315 MHz",
    notes:
      "Subaru Crosstrek smart key system (2nd gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Subaru",
    model: "Ascent",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB4", "SUBE4"],
    frequency: "315 MHz",
    notes: "Subaru Ascent smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Subaru",
    model: "Legacy",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB5", "SUBE5"],
    frequency: "315 MHz",
    notes: "Subaru Legacy smart key system (6th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Subaru",
    model: "WRX",
    yearStart: 2015,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB6", "SUBE6"],
    frequency: "315 MHz",
    notes: "Subaru WRX smart key system (4th gen) with backup transponder",
    dualSystem: true,
  },
  {
    make: "Subaru",
    model: "BRZ",
    yearStart: 2012,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUB66", "ID33"],
    compatibleParts: ["SUB7", "SUBE7"],
    frequency: "315 MHz",
    notes: "Subaru BRZ smart key system (1st gen) with backup transponder",
    dualSystem: true,
  },
];
