export const suzukiTransponderData = [
  {
    make: "Suzuki",
    model: "SX4",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUZ66"],
    compatibleParts: ["SUZX", "SUZEX"],
    frequency: "315 MHz",
    notes: "Suzuki SX4 smart key system",
    dualSystem: false,
  },
  {
    make: "Suzuki",
    model: "Vitara",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "SUZ68"],
    compatibleParts: ["SUZX2", "SUZEX2"],
    frequency: "315 MHz",
    notes: "Suzuki Vitara smart key system",
    dualSystem: false,
  },
  {
    make: "Suzuki",
    model: "Swift",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "SUZ66"],
    compatibleParts: ["SUZX", "SUZEX"],
    frequency: "315 MHz",
    notes: "Suzuki Swift smart key system",
    dualSystem: false,
  },
];
