export const toyotaTransponderData = [
  {
    make: "Toyota",
    model: "Camry",
    yearStart: 2018,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX", "TOYEX"],
    frequency: "315 MHz",
    notes: "Toyota Camry smart key system (XV70)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "Corolla",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX2", "TOYEX2"],
    frequency: "315 MHz",
    notes: "Toyota Corolla smart key system (E210)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "RAV4",
    yearStart: 2019,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX3", "TOYEX3"],
    frequency: "315 MHz",
    notes: "Toyota RAV4 smart key system (XA50)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "Highlander",
    yearStart: 2020,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX4", "TOYEX4"],
    frequency: "315 MHz",
    notes: "Toyota Highlander smart key system (XU70)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "Tacoma",
    yearStart: 2016,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX5", "TOYEX5"],
    frequency: "315 MHz",
    notes: "Toyota Tacoma smart key system (N300)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "Tundra",
    yearStart: 2022,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX6", "TOYEX6"],
    frequency: "315 MHz",
    notes: "Toyota Tundra smart key system (XK70)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "4Runner",
    yearStart: 2014,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX7", "TOYEX7"],
    frequency: "315 MHz",
    notes: "Toyota 4Runner smart key system (N280)",
    dualSystem: false,
  },
  {
    make: "Toyota",
    model: "Sienna",
    yearStart: 2021,
    yearEnd: 2024,
    transponderType: "Smart Key",
    chipType: ["ID46", "TOY66"],
    compatibleParts: ["TOYX8", "TOYEX8"],
    frequency: "315 MHz",
    notes: "Toyota Sienna smart key system (XL40)",
    dualSystem: false,
  },
];
