import { TransponderData } from "@/app/services/transponderService";

export const transponderUpdates2022: TransponderData[] = [
  // BMW Latest Models (2022+)
  {
    id: "BMW-3-SERIES-2022",
    make: "BMW",
    model: "3-SERIES",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "FBS4",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["66128870771", "66127628439"]),
    frequency: "434 MHz",
    notes: "Latest generation FBS4 system with rolling code",
    dualSystem: false,
  },
  // Audi Latest Models (2022+)
  {
    id: "AUDI-A4-2022",
    make: "AUDI",
    model: "A4",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "MQB",
    chipType: JSON.stringify(["HITAG-AES", "NCF29A1M"]),
    compatibleParts: JSON.stringify(["4M0959754BC", "4N0959754AJ"]),
    frequency: "433.92 MHz",
    notes: "MQB platform with latest generation AES encryption",
    dualSystem: false,
  },
  // Toyota Latest Models (2022+)
  {
    id: "TOYOTA-CAMRY-2022",
    make: "TOYOTA",
    model: "CAMRY",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "H",
    chipType: JSON.stringify(["H", "G", "DST80"]),
    compatibleParts: JSON.stringify(["89904-06081"]),
    frequency: "433.92 MHz",
    notes: "Latest generation H-type system",
    dualSystem: true,
  },
  // Honda Latest Models (2022+)
  {
    id: "HONDA-CIVIC-2022",
    make: "HONDA",
    model: "CIVIC",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "G",
    chipType: JSON.stringify(["G", "HON66"]),
    compatibleParts: JSON.stringify(["35118-T2A-A50"]),
    frequency: "433.92 MHz",
    notes: "Latest generation G-type system with improved security",
    dualSystem: true,
  },
  // Ford Latest Models (2022+)
  {
    id: "FORD-F150-2022",
    make: "FORD",
    model: "F-150",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "PEPS",
    chipType: JSON.stringify(["HITAG-AES", "4D63"]),
    compatibleParts: JSON.stringify(["HL3T-15K601-BC"]),
    frequency: "902 MHz",
    notes: "Latest PEPS system with high-frequency remote",
    dualSystem: true,
  },
  // Chevrolet Latest Models (2022+)
  {
    id: "CHEVROLET-SILVERADO-2022",
    make: "CHEVROLET",
    model: "SILVERADO",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "PEPS",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["13508771"]),
    frequency: "433.92 MHz",
    notes: "Latest generation PEPS with enhanced security",
    dualSystem: true,
  },
  // Hyundai Latest Models (2022+)
  {
    id: "HYUNDAI-TUCSON-2022",
    make: "HYUNDAI",
    model: "TUCSON",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "HITAG3",
    chipType: JSON.stringify(["HITAG3", "PCF7952"]),
    compatibleParts: JSON.stringify(["95440-3V000"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with smart key system",
    dualSystem: true,
  },
  // Kia Latest Models (2022+)
  {
    id: "KIA-SPORTAGE-2022",
    make: "KIA",
    model: "SPORTAGE",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "HITAG3",
    chipType: JSON.stringify(["HITAG3", "PCF7952"]),
    compatibleParts: JSON.stringify(["95440-P1100"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with smart key system",
    dualSystem: true,
  },
  // Nissan Latest Models (2022+)
  {
    id: "NISSAN-ROGUE-2022",
    make: "NISSAN",
    model: "ROGUE",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "NATS 6",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["285E3-6FL3A"]),
    frequency: "433.92 MHz",
    notes: "Latest NATS 6 system with enhanced security",
    dualSystem: true,
  },
  // Volkswagen Latest Models (2022+)
  {
    id: "VOLKSWAGEN-TIGUAN-2022",
    make: "VOLKSWAGEN",
    model: "TIGUAN",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "MQB",
    chipType: JSON.stringify(["HITAG-AES", "NCF29A1M"]),
    compatibleParts: JSON.stringify(["5WA959752BE"]),
    frequency: "433.92 MHz",
    notes: "MQB platform with latest generation AES encryption",
    dualSystem: false,
  },
  // Subaru Latest Models (2022+)
  {
    id: "SUBARU-OUTBACK-2022",
    make: "SUBARU",
    model: "OUTBACK",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "G",
    chipType: JSON.stringify(["G", "HITAG3"]),
    compatibleParts: JSON.stringify(["88835AL000"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with smart entry system",
    dualSystem: true,
  },
  // Land Rover Latest Models (2022+)
  {
    id: "LAND-ROVER-DEFENDER-2022",
    make: "LAND ROVER",
    model: "DEFENDER",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "HITAG-AES",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["LR135387"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with keyless entry",
    dualSystem: true,
  },
  // Dodge Latest Models (2022+)
  {
    id: "DODGE-RAM-2022",
    make: "DODGE",
    model: "RAM",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "FOBIK",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["68291689AB"]),
    frequency: "433.92 MHz",
    notes: "Latest generation FOBIK system",
    dualSystem: true,
  },
  // Chrysler Latest Models (2022+)
  {
    id: "CHRYSLER-300-2022",
    make: "CHRYSLER",
    model: "300",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "FOBIK",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["68291689AB"]),
    frequency: "433.92 MHz",
    notes: "Latest generation FOBIK system",
    dualSystem: true,
  },
  // Lexus Latest Models (2022+)
  {
    id: "LEXUS-RX-2022",
    make: "LEXUS",
    model: "RX",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "H",
    chipType: JSON.stringify(["H", "G", "DST80"]),
    compatibleParts: JSON.stringify(["89904-48V80"]),
    frequency: "433.92 MHz",
    notes: "Latest generation H-type system",
    dualSystem: true,
  },
  // Suzuki Latest Models (2022+)
  {
    id: "SUZUKI-VITARA-2022",
    make: "SUZUKI",
    model: "VITARA",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "ID47",
    chipType: JSON.stringify(["ID47", "PCF7939FA"]),
    compatibleParts: JSON.stringify(["37172-54P0"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with keyless system",
    dualSystem: true,
  },
  // Fiat Latest Models (2022+)
  {
    id: "FIAT-500X-2022",
    make: "FIAT",
    model: "500X",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "FOBIK",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["68291689AB"]),
    frequency: "433.92 MHz",
    notes: "Latest generation FOBIK system",
    dualSystem: true,
  },
  // Peugeot Latest Models (2022+)
  {
    id: "PEUGEOT-3008-2022",
    make: "PEUGEOT",
    model: "3008",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "VA2",
    chipType: JSON.stringify(["HITAG-AES", "PCF7953P"]),
    compatibleParts: JSON.stringify(["98 126 128 80"]),
    frequency: "433.92 MHz",
    notes: "Latest generation VA2 system",
    dualSystem: true,
  },
  // Acura Latest Models (2022+)
  {
    id: "ACURA-MDX-2022",
    make: "ACURA",
    model: "MDX",
    yearStart: 2022,
    yearEnd: null,
    transponderType: "G",
    chipType: JSON.stringify(["G", "HON66"]),
    compatibleParts: JSON.stringify(["72147-T2A-A11"]),
    frequency: "433.92 MHz",
    notes: "Latest generation G-type system",
    dualSystem: true,
  },
];
