export const transponderUpdates2022 = [
  {
    make: "BMW",
    model: "X7",
    yearStart: 2022,
    yearEnd: 2023,
    transponderType: "Smart Key",
    chipType: ["ID48", "BMW68"],
    compatibleParts: ["BMWX3", "BMWEX3"],
    frequency: "433 MHz",
    notes: "Updated BMW X7 smart key system for 2022",
    dualSystem: false,
  },
  {
    make: "Mercedes-Benz",
    model: "S-Class",
    yearStart: 2022,
    yearEnd: 2023,
    transponderType: "Smart Key",
    chipType: ["ID48", "MB68"],
    compatibleParts: ["MBX3", "MBEX3"],
    frequency: "433 MHz",
    notes: "Updated Mercedes-Benz S-Class smart key system for 2022",
    dualSystem: false,
  },
  {
    make: "Audi",
    model: "RS e-tron GT",
    yearStart: 2022,
    yearEnd: 2023,
    transponderType: "Smart Key",
    chipType: ["ID48", "4D48"],
    compatibleParts: ["AUDX3", "AUDEX3"],
    frequency: "433 MHz",
    notes: "New Audi RS e-tron GT smart key system for 2022",
    dualSystem: false,
  },
];
