import { TransponderData } from "@/app/services/transponderService";

export const volkswagenTransponderData: TransponderData[] = [
  {
    id: "VW-JETTA-2011-2018",
    make: "VOLKSWAGEN",
    model: "JETTA",
    yearStart: 2011,
    yearEnd: 2018,
    transponderType: "Megamos 48",
    chipType: JSON.stringify(["ID48", "MEGAMOS"]),
    compatibleParts: JSON.stringify(["5K0959753", "5K0959754"]),
    frequency: "315 MHz",
    notes: "MK6 generation",
    dualSystem: false,
  },
  {
    id: "VW-GOLF-2015-2020",
    make: "VOLKSWAGEN",
    model: "GOLF",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Megamos AES",
    chipType: JSON.stringify(["ID49", "MEGAMOS AES"]),
    compatibleParts: JSON.stringify(["5G0959753", "5G0959754"]),
    frequency: "433.92 MHz",
    notes: "MK7 generation with keyless entry",
    dualSystem: true,
  },
  {
    id: "VW-TIGUAN-2018-2023",
    make: "VOLKSWAGEN",
    model: "TIGUAN",
    yearStart: 2018,
    yearEnd: 2023,
    transponderType: "Megamos AES",
    chipType: JSON.stringify(["ID49", "MEGAMOS AES"]),
    compatibleParts: JSON.stringify(["5NA959753", "5NA959754"]),
    frequency: "433.92 MHz",
    notes: "Second generation with KESSY",
    dualSystem: true,
  },
  {
    id: "VW-ATLAS-2020",
    make: "VOLKSWAGEN",
    model: "ATLAS",
    yearStart: 2020,
    yearEnd: null,
    transponderType: "Megamos AES Pro",
    chipType: JSON.stringify(["ID49", "MEGAMOS AES Pro"]),
    compatibleParts: JSON.stringify(["3CN959753", "3CN959754"]),
    frequency: "433.92 MHz",
    notes: "Latest generation with advanced KESSY",
    dualSystem: true,
  },
];
