export const volkswagenTransponderData = [
  {
    make: "Volkswagen",
    model: "Jetta",
    yearStart: 2016,
    yearEnd: 2021,
    transponderType: "Smart Key",
    chipType: ["ID46", "VW66"],
    compatibleParts: ["VWX", "VWEX"],
    frequency: "433 MHz",
    notes: "Volkswagen Jetta smart key system",
    dualSystem: false,
  },
  {
    make: "Volkswagen",
    model: "Tiguan",
    yearStart: 2017,
    yearEnd: 2022,
    transponderType: "Smart Key",
    chipType: ["ID47", "VW68"],
    compatibleParts: ["VWX2", "VWEX2"],
    frequency: "433 MHz",
    notes: "Volkswagen Tiguan smart key system",
    dualSystem: false,
  },
  {
    make: "Volkswagen",
    model: "Passat",
    yearStart: 2015,
    yearEnd: 2020,
    transponderType: "Smart Key",
    chipType: ["ID46", "VW66"],
    compatibleParts: ["VWX", "VWEX"],
    frequency: "433 MHz",
    notes: "Volkswagen Passat smart key system",
    dualSystem: false,
  },
];
